model:
  model_path: /home/jianxin/jx_ws/lingbot-vla/checkpoints/lingbot-vla-4b
  tokenizer_path: /home/jianxin/jx_ws/lingbot-vla/checkpoints/qwen2.5-vl-3b-instruct
  post_training: true
  adanorm_time: true
  old_adanorm: true

data:
  datasets_type: vla
  data_name: robotwin_example
  train_path: /home/ss-oss1/data/user/shawks/lerobot_test_data/lerobot_video_03
  num_workers: 16
  norm_type: bounds_99_woclip
  norm_stats_file: assets/norm_stats/ego_pretrain_10k_norm.json #
  chunk_subset: null  # Only load chunk-000 to reduce dataset load (set to null for full data)
  episode_subset: null # inclusive e.g.[1,99]
train:
  output_dir:  /home/jianxin/jx_ws/lingbot-vla/output/aloha_test—16workers #
  loss_type: L1_fm
  data_parallel_mode: fsdp2
  enable_full_shard: false
  module_fsdp_enable: true
  use_compile: false
  use_wandb: true
  wandb_project: lingbot-vla-ego-pretrain
  wandb_name: aloha_test—16workers
  rmpad: false
  rmpad_with_pos_ids: false
  ulysses_parallel_size: 1
  freeze_vision_encoder: false
  tokenizer_max_length: 24
  action_dim: 14
  max_action_dim: 75
  max_state_dim: 75
  lr: 1.0e-4
  lr_decay_style: constant
  num_train_epochs: 10
  micro_batch_size: 32
  global_batch_size: 256
  max_steps: 100000
  ckpt_manager: dcp
  save_steps: 10000
  save_epochs: 10
  enable_fp32: true
  enable_resume: true