model:
  model_path: /path/to/LingBot-VLA
  tokenizer_path: /path/to/Qwen2.5-VL-3B-Instruct/

data:
  datasets_type: vla
  train_path: /home/jianxin/jx_ws/lerobot_data
  norm_path: assets/norm_stats/lerobot_data_norm.json

train:
  global_batch_size: 512
  output_dir: output/norm
